application:
  metrics:
    address: udp://localhost:8125
    prefix: zero

service:
  listeners:
    - name: http
      address: localhost:80
      socket_fd: 3
  runtime:
    name: example
    directory: /etc/example
    path: /usr/bin/example
    args:
      - '--config'
      - 'config.yaml'
    environment:
      - key: FOO
        value: bar
      - key: BAZ
  options:
    reload_signal: SIGUSR1
    reload_uptime: 5s
    shutdown_signal: SIGINT
    shutdown_timeout: 500s
