application:
  metrics:
    address: udp://localhost:8125
    prefix: unistore
  log:
    level: info
    outputs:
      - stdout
  errors:
    sentry_dsn: https://key@sentry.example.com/1

server:
  listener:
    address: tcp:localhost:5120
    max_active_connections: 1024
  rpc:
    max_recv_message_size: 104857600  # 100 MB
    max_send_message_size: 104857600  # 100 MB
  storage:
    disk:
      root: /var/object
      buffer:
        get_chunk_size: 4096  # 4 KB
        put_chunk_size: 4096  # 4 KB
      checksum:
        algorithm: sha256
      compression:
        algorithm: zstd
        level: 10
    unistore:
      address: unistore.service.example.com:5120
      backend: disk
      log:
        level: info
        outputs:
          - /var/log/unistore/unistore.log
    b2:
      application_key_id: b2_application_key_id
      application_key: b2_application_key
      bucket_aliases:
        - pattern: media
          alias: b2-media-12345
      bucket_permissions:
        - pattern: /^read-only-.+/
          rpc:
            head_object: true
            get_object: true
            stream_get_object: true
            list_objects: true
        - pattern: /^write-only-.+/
          rpc:
            put_object: true
            stream_put_object: true
            delete_object: true
      buffer:
        get_chunk_size: 5242880  # 5 MB
        put_chunk_size: 5242880  # 5 MB
      threshold:
        min_stream_put_size: 5242880  # 5 MB
      compression:
        algorithm: gzip
        level: 9
      encryption:
        name: b2-encrypt
        mechanism: age
        private_key: AGE-SECRET-KEY-1LQ4QSH0LY948QY363KEPSTCAH6HNR6ZDMA8RZHGCPFMYS9LRYDNQ7T9GKZ
        public_key: age1s7mwqal32elpdsnd7vuzlhhfl2rj8jeagpt4spjdktgdp6z9n9fsfd27d9
