application:
  metrics:
    address: udp://localhost:8125
    prefix: bitflow
  log:
    level: info

server:
  proxies:
    - name: smtp
      listener:
        address: localhost:25
        read_timeout: 30s
        write_timeout: 30s
        authorized_sources:
          - 127.0.0.1/32
          - 10.0.0.0/8
      target:
        address: mail.example.com:26
        connect_attempts: 5
        connect_backoff: 100ms
        connect_timeout: 5s
        read_timeout: 30s
        write_timeout: 30s
        keepalive_interval: 10s
      options:
        connection_limit: 5
        connection_lifetime: 30s
        connection_log: /var/log/bitflow/smtp.log
        enable_proxy_header: true
    - name: ssh
      listener:
        address: 0.0.0.0:22
      target:
        address: localhost:2222
        connect_timeout: 1s
        resolve_timeout: 100ms
      options:
        enable_dual_stack: true
    - name: http
      listener:
        address: unix:/var/run/http/http.sock
      target:
        address: web.example.com:80
        connect_timeout: 5s
