server:
  listen:
    transport: tcp
    address: localhost:20028
  livegrep:
    load_balancing_policy: round-robin
    request_timeout: 3000
    servers:
      - authority: livegrep
        address: localhost:20027
  metrics:
    # Omit this block to disable metrics reporting
    statsd:
      addr: localhost:8125
      prefix: webgrep
      sample_rate: 1.0
  logging:
    winston:
      level: info
      output: stdout
    supercharged:
      enabled: false
  cache:
    # Only include one of the blocks below, indicating the cache backend to use
    # Omit this block to disable cache
    redis:
      ttl: 300000
      prefix: webgrep
      socket: /var/run/redis/redis.sock
      timeout: 3000
    memory:
      ttl: 300000
  source:
    # Only include one of the blocks below, indicating the source code viewer backend to use
    # Omit this block to disable the source code viewer API
    local:
      repositories:
        - name: webgrep
          path: /repos/webgrep
    gitlab:
      base_url: https://gitlab.com
      access_token: gitlab-api-access-token

client:
  site:
    title: "{page} - {name} - webgrep"
  search:
    name: webgrep
    description: webgrep code search
    base_url: https://webgrep.example.com
  options:
    metadata_poll_interval: 600000
  resources:
    - title: webgrep on Github
      href: https://github.com/LINKIWI/webgrep
